### ISSUE TITLE
STITCH_target_drugsetlibrary_name.dmt ERROR

### ISSUE THREAD

**Issue by vallurumk** [MaayanLab/Drugmonizome#3]
Hi,

I got an error while downloading .dmt file.

Download link name
https://maayanlab-public.s3.amazonaws.com/drugmonizome-dmts/STITCH_target_drugsetlibrary_name.dmt

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>GMRAD20JVYEG40C2</RequestId>
<HostId>wKF6WXq0Zzfoidh1csg325G/CPDs+AkO0cdFN2S0YblJmmHe5B1RQhAHkTKfuBXqLNdgFnDQ8/8=</HostId>
</Error>

Can you please check this issue. 

Best wishes
Manoj

**Comment by ekropiwnicki** [comment]
Permissions were changed to allow for the download of these files.
