### ISSUE TITLE
Geneshot Predicted Enrichr Genes  - Drug name .dmt file error

### ISSUE THREAD

**Issue by vallurumk** [MaayanLab/Drugmonizome#4]
Hi,

Drug name .dmt file is a replica of the InChIKey .dmt file

InChIKey
https://maayanlab-public.s3.amazonaws.com/drugmonizome-dmts/Geneshot_predicted_enrichr_drugsetlibrary_inchikey.dmt
Drug name
https://maayanlab-public.s3.amazonaws.com/drugmonizome-dmts/Geneshot_predicted_enrichr_drugsetlibrary_inchikey.dmt

Can you please update it with the drug name .dmt file. 

Thank you!

Best wishes
Manoj

**Comment by ekropiwnicki** [comment]
Hi Manoj,
This has been fixed, sorry for the wait!
